arducopter:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
    
    
  # Position Controllers ---------------------------------------
  movable_mass_0_position_controller:
    type: effort_controllers/JointPositionController
    joint: stick_to_movable_mass_0
    pid: {p: 220.0, i: 10.0, d: 22.0, i_clamp_max: 50.0, i_clamp_min: -50.0}
  movable_mass_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: stick_to_movable_mass_1
    pid: {p: 220.0, i: 10.0, d: 22.0, i_clamp_max: 50.0, i_clamp_min: -50.0}
  movable_mass_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: stick_to_movable_mass_2
    pid: {p: 220.0, i: 10.0, d: 22.0, i_clamp_max: 50.0, i_clamp_min: -50.0}
  movable_mass_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: stick_to_movable_mass_3
    pid: {p: 220.0, i: 10.0, d: 22.0, i_clamp_max: 50.0, i_clamp_min: -50.0}
